{{- include "sam.validateApplicationPassword" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-persistence
  labels:
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.global.persistence.enabled }}
  WEB_UI_GATEWAY_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.webuiUser" .) (include "sam.database.webuiPassword" .) (include "postgresql.host" (index .Subcharts "persistence-layer")) (include "postgresql.port" (index .Subcharts "persistence-layer")) (include "sam.database.webuiName" .) | b64enc }}
  PLATFORM_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.platformUser" .) (include "sam.database.platformPassword" .) (include "postgresql.host" (index .Subcharts "persistence-layer")) (include "postgresql.port" (index .Subcharts "persistence-layer")) (include "sam.database.platformName" .) | b64enc }}
  ORCHESTRATOR_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.orchestratorUser" .) (include "sam.database.orchestratorPassword" .) (include "postgresql.host" (index .Subcharts "persistence-layer")) (include "postgresql.port" (index .Subcharts "persistence-layer")) (include "sam.database.orchestratorName" .) | b64enc }}
  {{- else }}
  WEB_UI_GATEWAY_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.qualifyUsername" (dict "username" (include "sam.database.webuiUser" .) "context" .)) (include "sam.database.webuiPassword" .) .Values.dataStores.database.host .Values.dataStores.database.port (include "sam.database.webuiName" .) | b64enc }}
  PLATFORM_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.qualifyUsername" (dict "username" (include "sam.database.platformUser" .) "context" .)) (include "sam.database.platformPassword" .) .Values.dataStores.database.host .Values.dataStores.database.port (include "sam.database.platformName" .) | b64enc }}
  ORCHESTRATOR_DATABASE_URL: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" (include "sam.database.qualifyUsername" (dict "username" (include "sam.database.orchestratorUser" .) "context" .)) (include "sam.database.orchestratorPassword" .) .Values.dataStores.database.host .Values.dataStores.database.port (include "sam.database.orchestratorName" .) | b64enc }}
  {{- end }}
  OBJECT_STORAGE_TYPE: {{ include "sam.objectStorage.type" . | b64enc }}
  {{- if eq (include "sam.objectStorage.type" .) "azure" }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.dataStores.azure.accountName | b64enc }}
  {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
  AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.dataStores.azure.accountKey | b64enc }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.dataStores.azure.connectionString | b64enc }}
  {{- end }}
  AZURE_STORAGE_CONTAINER_NAME: {{ include "sam.azure.containerName" . | b64enc }}
  CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.azure.connectorSpecContainerName" . | b64enc }}
  {{- else if eq (include "sam.objectStorage.type" .) "gcs" }}
  GCS_PROJECT: {{ .Values.dataStores.gcs.project | b64enc }}
  {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
  GCS_CREDENTIALS_JSON: {{ .Values.dataStores.gcs.credentialsJson | b64enc }}
  {{- end }}
  GCS_BUCKET_NAME: {{ include "sam.gcs.bucketName" . | b64enc }}
  CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.gcs.connectorSpecBucketName" . | b64enc }}
  {{- else }}
  S3_ENDPOINT_URL: {{ include "sam.s3.endpointUrl" . | b64enc }}
  S3_BUCKET_NAME: {{ include "sam.s3.bucketName" . | b64enc }}
  CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.s3.connectorSpecBucketName" . | b64enc }}
  {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
  AWS_ACCESS_KEY_ID: {{ include "sam.s3.accessKey" . | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ include "sam.s3.secretKey" . | b64enc }}
  {{- end }}
  AWS_REGION: {{ .Values.dataStores.s3.region | default "us-east-1" | b64enc }}
  {{- end }}
  ORCHESTRATOR_SESSION_SERVICE_TYPE: {{ print "sql" | b64enc }}
  WEB_UI_SESSION_SERVICE_TYPE: {{ print "sql" | b64enc }}
