{{- if not .Values.global.persistence.enabled }}
{{- $storageType := include "sam.objectStorage.type" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-storage
  labels:
    app.kubernetes.io/service: {{ $storageType }}
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq $storageType "azure" }}
    AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.dataStores.azure.accountName | b64enc }}
    {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
    AZURE_STORAGE_ACCOUNT_KEY: {{ .Values.dataStores.azure.accountKey | b64enc }}
    AZURE_STORAGE_CONNECTION_STRING: {{ .Values.dataStores.azure.connectionString | b64enc }}
    {{- end }}
    AZURE_STORAGE_CONTAINER_NAME: {{ include "sam.azure.containerName" . | b64enc }}
    CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.azure.connectorSpecContainerName" . | b64enc }}
  {{- else if eq $storageType "gcs" }}
    GCS_PROJECT: {{ .Values.dataStores.gcs.project | b64enc }}
    {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
    GCS_CREDENTIALS_JSON: {{ .Values.dataStores.gcs.credentialsJson | b64enc }}
    {{- end }}
    GCS_BUCKET_NAME: {{ include "sam.gcs.bucketName" . | b64enc }}
    CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.gcs.connectorSpecBucketName" . | b64enc }}
  {{- else }}
    S3_ENDPOINT_URL: {{ include "sam.s3.endpointUrl" . | b64enc }}
    S3_BUCKET_NAME: {{ include "sam.s3.bucketName" . | b64enc }}
    CONNECTOR_SPEC_BUCKET_NAME: {{ include "sam.s3.connectorSpecBucketName" . | b64enc }}
    {{- if not .Values.dataStores.objectStorage.workloadIdentity.enabled }}
    S3_ACCESS_KEY: {{ include "sam.s3.accessKey" . | b64enc }}
    S3_SECRET_KEY: {{ include "sam.s3.secretKey" . | b64enc }}
    {{- end }}
    AWS_REGION: {{ .Values.dataStores.s3.region | default "us-east-1" | b64enc }}
  {{- end }}
{{- end }}
