apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.samDeployment.serviceAccount.name }}
  {{- with .Values.samDeployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.samDeployment.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.samDeployment.imagePullSecret }}
{{- end }}
